//! Resource Schema Definitions
//!
//! Defines the Terraform schema for all InfraSim resources.

use crate::generated::tfplugin6::{Schema, schema};

/// Create the schema for infrasim_network resource
pub fn network_schema() -> Schema {
    Schema {
        version: 1,
        block: Some(schema::Block {
            version: 1,
            description: "InfraSim Network resource".to_string(),
            description_kind: schema::StringKind::Plain as i32,
            deprecated: false,
            attributes: vec![
                schema::Attribute {
                    name: "id".to_string(),
                    r#type: serde_json::to_vec(&"string").unwrap(),
                    nested_type: None,
                    description: "Network ID".to_string(),
                    description_kind: schema::StringKind::Plain as i32,
                    required: false,
                    optional: false,
                    computed: true,
                    sensitive: false,
                    deprecated: false,
                },
                schema::Attribute {
                    name: "name".to_string(),
                    r#type: serde_json::to_vec(&"string").unwrap(),
                    nested_type: None,
                    description: "Network name".to_string(),
                    description_kind: schema::StringKind::Plain as i32,
                    required: true,
                    optional: false,
                    computed: false,
                    sensitive: false,
                    deprecated: false,
                },
                schema::Attribute {
                    name: "mode".to_string(),
                    r#type: serde_json::to_vec(&"string").unwrap(),
                    nested_type: None,
                    description: "Network mode (nat, bridge, isolated)".to_string(),
                    description_kind: schema::StringKind::Plain as i32,
                    required: false,
                    optional: true,
                    computed: true,
                    sensitive: false,
                    deprecated: false,
                },
                schema::Attribute {
                    name: "cidr".to_string(),
                    r#type: serde_json::to_vec(&"string").unwrap(),
                    nested_type: None,
                    description: "Network CIDR (e.g., 192.168.100.0/24)".to_string(),
                    description_kind: schema::StringKind::Plain as i32,
                    required: true,
                    optional: false,
                    computed: false,
                    sensitive: false,
                    deprecated: false,
                },
                schema::Attribute {
                    name: "gateway".to_string(),
                    r#type: serde_json::to_vec(&"string").unwrap(),
                    nested_type: None,
                    description: "Gateway IP address".to_string(),
                    description_kind: schema::StringKind::Plain as i32,
                    required: false,
                    optional: true,
                    computed: true,
                    sensitive: false,
                    deprecated: false,
                },
                schema::Attribute {
                    name: "dhcp_start".to_string(),
                    r#type: serde_json::to_vec(&"string").unwrap(),
                    nested_type: None,
                    description: "DHCP range start".to_string(),
                    description_kind: schema::StringKind::Plain as i32,
                    required: false,
                    optional: true,
                    computed: true,
                    sensitive: false,
                    deprecated: false,
                },
                schema::Attribute {
                    name: "dhcp_end".to_string(),
                    r#type: serde_json::to_vec(&"string").unwrap(),
                    nested_type: None,
                    description: "DHCP range end".to_string(),
                    description_kind: schema::StringKind::Plain as i32,
                    required: false,
                    optional: true,
                    computed: true,
                    sensitive: false,
                    deprecated: false,
                },
                schema::Attribute {
                    name: "mtu".to_string(),
                    r#type: serde_json::to_vec(&"number").unwrap(),
                    nested_type: None,
                    description: "MTU size".to_string(),
                    description_kind: schema::StringKind::Plain as i32,
                    required: false,
                    optional: true,
                    computed: true,
                    sensitive: false,
                    deprecated: false,
                },
            ],
            block_types: vec![],
        }),
    }
}

/// Create the schema for infrasim_vm resource
pub fn vm_schema() -> Schema {
    Schema {
        version: 1,
        block: Some(schema::Block {
            version: 1,
            description: "InfraSim Virtual Machine resource".to_string(),
            description_kind: schema::StringKind::Plain as i32,
            deprecated: false,
            attributes: vec![
                schema::Attribute {
                    name: "id".to_string(),
                    r#type: serde_json::to_vec(&"string").unwrap(),
                    nested_type: None,
                    description: "VM ID".to_string(),
                    description_kind: schema::StringKind::Plain as i32,
                    required: false,
                    optional: false,
                    computed: true,
                    sensitive: false,
                    deprecated: false,
                },
                schema::Attribute {
                    name: "name".to_string(),
                    r#type: serde_json::to_vec(&"string").unwrap(),
                    nested_type: None,
                    description: "VM name".to_string(),
                    description_kind: schema::StringKind::Plain as i32,
                    required: true,
                    optional: false,
                    computed: false,
                    sensitive: false,
                    deprecated: false,
                },
                schema::Attribute {
                    name: "cpus".to_string(),
                    r#type: serde_json::to_vec(&"number").unwrap(),
                    nested_type: None,
                    description: "Number of CPUs".to_string(),
                    description_kind: schema::StringKind::Plain as i32,
                    required: false,
                    optional: true,
                    computed: true,
                    sensitive: false,
                    deprecated: false,
                },
                schema::Attribute {
                    name: "memory".to_string(),
                    r#type: serde_json::to_vec(&"number").unwrap(),
                    nested_type: None,
                    description: "Memory in MB".to_string(),
                    description_kind: schema::StringKind::Plain as i32,
                    required: false,
                    optional: true,
                    computed: true,
                    sensitive: false,
                    deprecated: false,
                },
                schema::Attribute {
                    name: "disk".to_string(),
                    r#type: serde_json::to_vec(&"string").unwrap(),
                    nested_type: None,
                    description: "Disk image path".to_string(),
                    description_kind: schema::StringKind::Plain as i32,
                    required: true,
                    optional: false,
                    computed: false,
                    sensitive: false,
                    deprecated: false,
                },
                schema::Attribute {
                    name: "network_id".to_string(),
                    r#type: serde_json::to_vec(&"string").unwrap(),
                    nested_type: None,
                    description: "Network ID to attach".to_string(),
                    description_kind: schema::StringKind::Plain as i32,
                    required: false,
                    optional: true,
                    computed: false,
                    sensitive: false,
                    deprecated: false,
                },
                schema::Attribute {
                    name: "cloud_init".to_string(),
                    r#type: serde_json::to_vec(&"string").unwrap(),
                    nested_type: None,
                    description: "Cloud-init user data (base64)".to_string(),
                    description_kind: schema::StringKind::Plain as i32,
                    required: false,
                    optional: true,
                    computed: false,
                    sensitive: false,
                    deprecated: false,
                },
                schema::Attribute {
                    name: "vnc_port".to_string(),
                    r#type: serde_json::to_vec(&"number").unwrap(),
                    nested_type: None,
                    description: "VNC port".to_string(),
                    description_kind: schema::StringKind::Plain as i32,
                    required: false,
                    optional: false,
                    computed: true,
                    sensitive: false,
                    deprecated: false,
                },
                schema::Attribute {
                    name: "console_url".to_string(),
                    r#type: serde_json::to_vec(&"string").unwrap(),
                    nested_type: None,
                    description: "Web console URL".to_string(),
                    description_kind: schema::StringKind::Plain as i32,
                    required: false,
                    optional: false,
                    computed: true,
                    sensitive: false,
                    deprecated: false,
                },
                schema::Attribute {
                    name: "state".to_string(),
                    r#type: serde_json::to_vec(&"string").unwrap(),
                    nested_type: None,
                    description: "VM state".to_string(),
                    description_kind: schema::StringKind::Plain as i32,
                    required: false,
                    optional: false,
                    computed: true,
                    sensitive: false,
                    deprecated: false,
                },
                schema::Attribute {
                    name: "ip_address".to_string(),
                    r#type: serde_json::to_vec(&"string").unwrap(),
                    nested_type: None,
                    description: "IP address".to_string(),
                    description_kind: schema::StringKind::Plain as i32,
                    required: false,
                    optional: false,
                    computed: true,
                    sensitive: false,
                    deprecated: false,
                },
                // QoS attributes
                schema::Attribute {
                    name: "qos_latency_ms".to_string(),
                    r#type: serde_json::to_vec(&"number").unwrap(),
                    nested_type: None,
                    description: "Network latency in milliseconds".to_string(),
                    description_kind: schema::StringKind::Plain as i32,
                    required: false,
                    optional: true,
                    computed: false,
                    sensitive: false,
                    deprecated: false,
                },
                schema::Attribute {
                    name: "qos_jitter_ms".to_string(),
                    r#type: serde_json::to_vec(&"number").unwrap(),
                    nested_type: None,
                    description: "Network jitter in milliseconds".to_string(),
                    description_kind: schema::StringKind::Plain as i32,
                    required: false,
                    optional: true,
                    computed: false,
                    sensitive: false,
                    deprecated: false,
                },
                schema::Attribute {
                    name: "qos_loss_percent".to_string(),
                    r#type: serde_json::to_vec(&"number").unwrap(),
                    nested_type: None,
                    description: "Packet loss percentage".to_string(),
                    description_kind: schema::StringKind::Plain as i32,
                    required: false,
                    optional: true,
                    computed: false,
                    sensitive: false,
                    deprecated: false,
                },
                schema::Attribute {
                    name: "qos_bandwidth_mbps".to_string(),
                    r#type: serde_json::to_vec(&"number").unwrap(),
                    nested_type: None,
                    description: "Bandwidth limit in Mbps".to_string(),
                    description_kind: schema::StringKind::Plain as i32,
                    required: false,
                    optional: true,
                    computed: false,
                    sensitive: false,
                    deprecated: false,
                },
            ],
            block_types: vec![],
        }),
    }
}

/// Create the schema for infrasim_volume resource
pub fn volume_schema() -> Schema {
    Schema {
        version: 1,
        block: Some(schema::Block {
            version: 1,
            description: "InfraSim Volume resource".to_string(),
            description_kind: schema::StringKind::Plain as i32,
            deprecated: false,
            attributes: vec![
                schema::Attribute {
                    name: "id".to_string(),
                    r#type: serde_json::to_vec(&"string").unwrap(),
                    nested_type: None,
                    description: "Volume ID".to_string(),
                    description_kind: schema::StringKind::Plain as i32,
                    required: false,
                    optional: false,
                    computed: true,
                    sensitive: false,
                    deprecated: false,
                },
                schema::Attribute {
                    name: "name".to_string(),
                    r#type: serde_json::to_vec(&"string").unwrap(),
                    nested_type: None,
                    description: "Volume name".to_string(),
                    description_kind: schema::StringKind::Plain as i32,
                    required: true,
                    optional: false,
                    computed: false,
                    sensitive: false,
                    deprecated: false,
                },
                schema::Attribute {
                    name: "size_gb".to_string(),
                    r#type: serde_json::to_vec(&"number").unwrap(),
                    nested_type: None,
                    description: "Size in GB".to_string(),
                    description_kind: schema::StringKind::Plain as i32,
                    required: true,
                    optional: false,
                    computed: false,
                    sensitive: false,
                    deprecated: false,
                },
                schema::Attribute {
                    name: "format".to_string(),
                    r#type: serde_json::to_vec(&"string").unwrap(),
                    nested_type: None,
                    description: "Volume format (qcow2, raw)".to_string(),
                    description_kind: schema::StringKind::Plain as i32,
                    required: false,
                    optional: true,
                    computed: true,
                    sensitive: false,
                    deprecated: false,
                },
                schema::Attribute {
                    name: "base_image".to_string(),
                    r#type: serde_json::to_vec(&"string").unwrap(),
                    nested_type: None,
                    description: "Base image for copy-on-write".to_string(),
                    description_kind: schema::StringKind::Plain as i32,
                    required: false,
                    optional: true,
                    computed: false,
                    sensitive: false,
                    deprecated: false,
                },
                schema::Attribute {
                    name: "path".to_string(),
                    r#type: serde_json::to_vec(&"string").unwrap(),
                    nested_type: None,
                    description: "Volume file path".to_string(),
                    description_kind: schema::StringKind::Plain as i32,
                    required: false,
                    optional: false,
                    computed: true,
                    sensitive: false,
                    deprecated: false,
                },
                schema::Attribute {
                    name: "sha256".to_string(),
                    r#type: serde_json::to_vec(&"string").unwrap(),
                    nested_type: None,
                    description: "SHA256 hash of the volume".to_string(),
                    description_kind: schema::StringKind::Plain as i32,
                    required: false,
                    optional: false,
                    computed: true,
                    sensitive: false,
                    deprecated: false,
                },
            ],
            block_types: vec![],
        }),
    }
}

/// Create the schema for infrasim_snapshot resource
pub fn snapshot_schema() -> Schema {
    Schema {
        version: 1,
        block: Some(schema::Block {
            version: 1,
            description: "InfraSim Snapshot resource".to_string(),
            description_kind: schema::StringKind::Plain as i32,
            deprecated: false,
            attributes: vec![
                schema::Attribute {
                    name: "id".to_string(),
                    r#type: serde_json::to_vec(&"string").unwrap(),
                    nested_type: None,
                    description: "Snapshot ID".to_string(),
                    description_kind: schema::StringKind::Plain as i32,
                    required: false,
                    optional: false,
                    computed: true,
                    sensitive: false,
                    deprecated: false,
                },
                schema::Attribute {
                    name: "name".to_string(),
                    r#type: serde_json::to_vec(&"string").unwrap(),
                    nested_type: None,
                    description: "Snapshot name".to_string(),
                    description_kind: schema::StringKind::Plain as i32,
                    required: true,
                    optional: false,
                    computed: false,
                    sensitive: false,
                    deprecated: false,
                },
                schema::Attribute {
                    name: "vm_id".to_string(),
                    r#type: serde_json::to_vec(&"string").unwrap(),
                    nested_type: None,
                    description: "VM ID to snapshot".to_string(),
                    description_kind: schema::StringKind::Plain as i32,
                    required: true,
                    optional: false,
                    computed: false,
                    sensitive: false,
                    deprecated: false,
                },
                schema::Attribute {
                    name: "include_memory".to_string(),
                    r#type: serde_json::to_vec(&"bool").unwrap(),
                    nested_type: None,
                    description: "Include memory state".to_string(),
                    description_kind: schema::StringKind::Plain as i32,
                    required: false,
                    optional: true,
                    computed: true,
                    sensitive: false,
                    deprecated: false,
                },
                schema::Attribute {
                    name: "description".to_string(),
                    r#type: serde_json::to_vec(&"string").unwrap(),
                    nested_type: None,
                    description: "Snapshot description".to_string(),
                    description_kind: schema::StringKind::Plain as i32,
                    required: false,
                    optional: true,
                    computed: false,
                    sensitive: false,
                    deprecated: false,
                },
                schema::Attribute {
                    name: "size_bytes".to_string(),
                    r#type: serde_json::to_vec(&"number").unwrap(),
                    nested_type: None,
                    description: "Snapshot size in bytes".to_string(),
                    description_kind: schema::StringKind::Plain as i32,
                    required: false,
                    optional: false,
                    computed: true,
                    sensitive: false,
                    deprecated: false,
                },
                schema::Attribute {
                    name: "created_at".to_string(),
                    r#type: serde_json::to_vec(&"string").unwrap(),
                    nested_type: None,
                    description: "Creation timestamp".to_string(),
                    description_kind: schema::StringKind::Plain as i32,
                    required: false,
                    optional: false,
                    computed: true,
                    sensitive: false,
                    deprecated: false,
                },
            ],
            block_types: vec![],
        }),
    }
}

/// Create the provider schema
pub fn provider_schema() -> Schema {
    Schema {
        version: 1,
        block: Some(schema::Block {
            version: 1,
            description: "InfraSim Provider configuration".to_string(),
            description_kind: schema::StringKind::Plain as i32,
            deprecated: false,
            attributes: vec![
                schema::Attribute {
                    name: "daemon_address".to_string(),
                    r#type: serde_json::to_vec(&"string").unwrap(),
                    nested_type: None,
                    description: "Address of the InfraSim daemon".to_string(),
                    description_kind: schema::StringKind::Plain as i32,
                    required: false,
                    optional: true,
                    computed: true,
                    sensitive: false,
                    deprecated: false,
                },
            ],
            block_types: vec![],
        }),
    }
}
